### ISSUE TITLE
Compiled on "too modern" version of Java

### ISSUE THREAD

**Issue by SXRWahrheit** [SimpleMC/SimpleReserve#5]
Hi, I get this error on startup:

```
[12:18:50] [Server thread/ERROR]: Could not load 'plugins\simplereserve-1.0.0.jar' in folder 'plugins'
org.bukkit.plugin.InvalidPluginException: java.lang.UnsupportedClassVersionError: org/simplemc/simplereserve/SimpleReserve has been compiled by a more recent version of the Java Runtime (class file version 55.0), this version of the Java Runtime only recognizes class file versions up to 52.0
	at org.bukkit.plugin.java.JavaPluginLoader.loadPlugin(JavaPluginLoader.java:139) ~[server.jar:git-Spigot-ad703da-d77f4d9]
	at org.bukkit.plugin.SimplePluginManager.loadPlugin(SimplePluginManager.java:394) ~[server.jar:git-Spigot-ad703da-d77f4d9]
	at org.bukkit.plugin.SimplePluginManager.loadPlugins(SimplePluginManager.java:301) ~[server.jar:git-Spigot-ad703da-d77f4d9]
	at org.bukkit.craftbukkit.v1_16_R1.CraftServer.loadPlugins(CraftServer.java:380) ~[server.jar:git-Spigot-ad703da-d77f4d9]
	at net.minecraft.server.v1_16_R1.DedicatedServer.init(DedicatedServer.java:186) ~[server.jar:git-Spigot-ad703da-d77f4d9]
	at net.minecraft.server.v1_16_R1.MinecraftServer.v(MinecraftServer.java:810) ~[server.jar:git-Spigot-ad703da-d77f4d9]
	at net.minecraft.server.v1_16_R1.MinecraftServer.lambda$0(MinecraftServer.java:164) ~[server.jar:git-Spigot-ad703da-d77f4d9]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_241]
Caused by: java.lang.UnsupportedClassVersionError: org/simplemc/simplereserve/SimpleReserve has been compiled by a more recent version of the Java Runtime (class file version 55.0), this version of the Java Runtime only recognizes class file versions up to 52.0
	at java.lang.ClassLoader.defineClass1(Native Method) ~[?:1.8.0_241]
	at java.lang.ClassLoader.defineClass(Unknown Source) ~[?:1.8.0_241]
	at java.security.SecureClassLoader.defineClass(Unknown Source) ~[?:1.8.0_241]
	at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:163) ~[server.jar:git-Spigot-ad703da-d77f4d9]
	at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:96) ~[server.jar:git-Spigot-ad703da-d77f4d9]
	at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_241]
	at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_241]
	at java.lang.Class.forName0(Native Method) ~[?:1.8.0_241]
	at java.lang.Class.forName(Unknown Source) ~[?:1.8.0_241]
	at org.bukkit.plugin.java.PluginClassLoader.<init>(PluginClassLoader.java:64) ~[server.jar:git-Spigot-ad703da-d77f4d9]
	at org.bukkit.plugin.java.JavaPluginLoader.loadPlugin(JavaPluginLoader.java:135) ~[server.jar:git-Spigot-ad703da-d77f4d9]
	... 7 more
```

A quick search online suggests that this is because you compiled the plugin with Java 11, while the standard Minecraft version is Java 8. Could you please release a Java 8 version? Thanks!

**Comment by tajobe** [comment]
I've switched back from targeting java 11 to 1.8 in #6 as there's not a strict need for us to use java 11 but I would encourage you to update your runtime. Both the MC server software and Spigot run perfectly fine on Java 11 and it's the most current supported LTS.

**Comment by tajobe** [comment]
@SXRWahrheit Please see [release-1.0.1](https://github.com/SimpleMC/SimpleReserve/releases/tag/release-1.0.1)

**Comment by SXRWahrheit** [comment]
Thanks.
